//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecommercedbEntities : DbContext
    {
        public ecommercedbEntities()
            : base("name=ecommercedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcart> tblcarts { get; set; }
        public virtual DbSet<tblcategory> tblcategories { get; set; }
        public virtual DbSet<tblcoupon> tblcoupons { get; set; }
        public virtual DbSet<tbllogin> tbllogins { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblpurchase> tblpurchases { get; set; }
        public virtual DbSet<tblpurchasedetail> tblpurchasedetails { get; set; }
        public virtual DbSet<tblregistration> tblregistrations { get; set; }
        public virtual DbSet<tblstockdetail> tblstockdetails { get; set; }
    }
}
