//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcoupon
    {
        public int couponid { get; set; }
        public string couponcode { get; set; }
        public Nullable<decimal> discountamount { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<bool> isactive { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
    }
}
