//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcart
    {
        public int cartid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> addeddate { get; set; }
        public Nullable<bool> ispurchased { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
        public virtual tblproduct tblproduct { get; set; }
    }
}
