//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class tblproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproduct()
        {
            this.tblcarts = new HashSet<tblcart>();
            this.tblpurchasedetails = new HashSet<tblpurchasedetail>();
            this.tblstockdetails = new HashSet<tblstockdetail>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<decimal> price { get; set; }
        public string imageurl { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string status { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }
        public int Quantity { get; set; }
    
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcart> tblcarts { get; set; }
        public virtual tblcategory tblcategory { get; set; }
        public virtual tbllogin tbllogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpurchasedetail> tblpurchasedetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstockdetail> tblstockdetails { get; set; }
    }
}
