//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpurchase()
        {
            this.tblpurchasedetails = new HashSet<tblpurchasedetail>();
        }
    
        public int purchaseid { get; set; }
        public string invoicenumber { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public Nullable<decimal> discountamount { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblpurchasedetail> tblpurchasedetails { get; set; }
    }
}
