//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblregistration
    {
        public int registrationid { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public string addressline1 { get; set; }
        public string addresslin2 { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string pin { get; set; }
        public string email { get; set; }
        public bool isactive { get; set; }
        public System.DateTime createddate { get; set; }
    
        public virtual tbllogin tbllogin { get; set; }
    }
}
